# name: Cargo-audit, lint and test

# on:
#   push:
#     branches: main
#   pull_request:
#     branches: main

# defaults:
#   run:
#     shell: bash
#     working-directory: .

# env:
#   CARGO_TERM_COLOR: always
#   RUST_TOOLCHAIN: stable

# jobs: